version: '3.8'

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  portainer:
    image: portainer/portainer:${PORTAINER_VERSION}
    container_name: portainer
    restart: always
    privileged: true
    networks:
      - app
    ports:
      - ${PORTAINER_PORT}:${PORTAINER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - ./portainer/pwd:/pwd
    commandpassgenport  
    <<: *logging 

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/letsencrypt/live/${server_name}
      - ./nginx/conf.d:/etc/nginx/conf.d
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - app
    ports:
      - "80:80"
      - "443:443"
    links:
      - portainer  
    <<: *logging

  haproxy:
    image: haproxy:2.1.4
    container_name: haproxy
    networks:
      - app
    ports:
      - ${HAPROXY_PORT}:${HAPROXY_PORT}
    expose:
      - ${HAPROXY_PORT}
    volumes:
      - ./haproxy/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./cert:/etc/ssl/main
    links:
       - portainer
       - socks
    <<: *logging
  
  socks:
    image: mashiroota/microsocks:$${socks_verion}
    container_name: socks
    networks:
      - app
    ports:
      - 1080:1080
    expose:
      - 1080
    environment:
      - USER=$${socks_username}
      - PASSWORD=$${socks_password}
    <<: *logging      

networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28
    