apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    basicAuth: true
    basicAuthUser: ${INFLUXDB_USER}
    basicAuthPassword: ${INFLUXDB_USER_PASSWORD}
    database: app_metric
    user: ${INFLUXDB_USER}
    password: ${INFLUXDB_USER_PASSWORD}
    isDefault: false
    editable: false
