{
 "title": "Nginx-PROM",
 "description": "NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "NGINX CPU ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container_label_com_docker_swarm_service_name=\"app_webserver\"}[1m]) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100)"
    }
   ]
  },
  {
   "title": "NGINX MEMORY",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",container_label_com_docker_swarm_service_name=\"app_webserver\"})"
    }
   ]
  },
  {
   "title": "NGINX NET",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=\"app_webserver\"}[1m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=\"app_webserver\"}[1m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "irate(nginx_connections_handled[5m])",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "active" },
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nginx_connections_waiting", "legendFormat": "waiting" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total[5m])",
     "legendFormat": "total requests"
    }
   ]
  }
 ]
}